# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/project_constrains.xdc

# Block Designs: bd/casio_ur_IP/casio_ur_IP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP || ORIG_REF_NAME==casio_ur_IP} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_processing_system7_0_0/casio_ur_IP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_processing_system7_0_0 || ORIG_REF_NAME==casio_ur_IP_processing_system7_0_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_ps7_0_axi_periph_0/casio_ur_IP_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_ps7_0_axi_periph_0 || ORIG_REF_NAME==casio_ur_IP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_rst_ps7_0_100M_0/casio_ur_IP_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_rst_ps7_0_100M_0 || ORIG_REF_NAME==casio_ur_IP_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_timer_0_0/casio_ur_IP_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_timer_0_0 || ORIG_REF_NAME==casio_ur_IP_axi_timer_0_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_timer_1_0/casio_ur_IP_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_timer_1_0 || ORIG_REF_NAME==casio_ur_IP_axi_timer_1_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_xlconcat_0_0/casio_ur_IP_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_xlconcat_0_0 || ORIG_REF_NAME==casio_ur_IP_xlconcat_0_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_xbar_0/casio_ur_IP_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_xbar_0 || ORIG_REF_NAME==casio_ur_IP_xbar_0} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_gpio_0_1/casio_ur_IP_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_gpio_0_1 || ORIG_REF_NAME==casio_ur_IP_axi_gpio_0_1} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_gpio_1_1/casio_ur_IP_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_gpio_1_1 || ORIG_REF_NAME==casio_ur_IP_axi_gpio_1_1} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_gpio_2_1/casio_ur_IP_axi_gpio_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_gpio_2_1 || ORIG_REF_NAME==casio_ur_IP_axi_gpio_2_1} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_axi_gpio_3_1/casio_ur_IP_axi_gpio_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_axi_gpio_3_1 || ORIG_REF_NAME==casio_ur_IP_axi_gpio_3_1} -quiet] -quiet

# IP: bd/casio_ur_IP/ip/casio_ur_IP_auto_pc_0/casio_ur_IP_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==casio_ur_IP_auto_pc_0 || ORIG_REF_NAME==casio_ur_IP_auto_pc_0} -quiet] -quiet

# XDC: bd/casio_ur_IP/casio_ur_IP_ooc.xdc
