set_property SRC_FILE_INFO {cfile:C:/vivado_projects/casio_ur_2/casio_ur_2.srcs/constrs_1/new/project_constrains.xdc rfile:../../../casio_ur_2.srcs/constrs_1/new/project_constrains.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_io[3]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {gpio_rtl_tri_io[2]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {gpio_rtl_tri_io[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {gpio_rtl_tri_io[0]}]
